Dev
mrjvs/42-transcendence pull request #23
Opened 2021-06-10 10:45 UTC by wbarendr

Pull Request of Guilds and guildrequests. notes on these models and modules would be appreciated
Wars are in progress and this is not the latests version of the wars, notes won't be necessary here.

2021-06-11 11:00 UTC, mrjvs requested changes

2021-06-11 11:00 UTC, mrjvs commented on vivid-server/src/modules/guildrequest/guildrequest.service.ts
> +    console.log(userId);
remove debug log

2021-06-11 11:00 UTC, mrjvs commented on vivid-server/src/modules/guilds/guilds.controller.ts
> +    if (anagram.length > 5) throw new BadRequestException();
make sure anagrams are only valid characters (use a regex like `/^[A-Z1-9\-]{1,5}$/g`)

2021-06-11 11:00 UTC, mrjvs commented on vivid-server/src/modules/guilds/guilds.controller.ts
> +    if (anagram.length > 5) throw new BadRequestException();
(cuz urls can also have stuff like null characters in the middle)

2021-06-11 11:00 UTC, mrjvs commented on vivid-server/src/modules/users/user.service.ts
> +        if (error.code === '22P02') throw new NotFoundException();
add default throw and remove void from return value

2021-06-11 11:00 UTC, mrjvs commented on vivid-server/src/modules/guilds/guilds.service.ts
> +    console.log('winner: ', guildAnagram, points);
remove debug log

2021-06-11 11:00 UTC, mrjvs commented on vivid-server/src/models/user.entity.ts
> +  guild_anagram: string;
dont save the anagram on the user, that can cause desyncs. instead use a relation (check joined_channels for example)

2021-06-11 11:00 UTC, mrjvs commented on vivid-server/package.json
> +    "dto-mapping": "^1.1.0",
what do you use dto-mapping for?

2021-06-11 11:01 UTC, mrjvs commented
also make sure to fix the linting before merge

2021-06-11 11:19 UTC, pmerku requested changes

2021-06-11 11:19 UTC, pmerku commented on vivid-server/src/modules/users/user.service.ts
> +      });
Default throw to add, and remove void from return type

2021-06-11 11:19 UTC, pmerku commented on vivid-server/src/models/user-update.dto.ts
> +  name: string;
You can add a decorator from `class-validator` package to constrain the string like:
```ts
@IsNotEmpty()
name: string;
```

2021-06-11 11:20 UTC, pmerku commented on vivid-server/src/modules/users/user.service.ts
> +      });
Ah I see Jelle found it too

2021-06-16 08:59 UTC, pmerku approved these changes

2021-06-17 15:23 UTC, mrjvs approved these changes

2021-06-17 15:23 UTC, merged