Pong multiplayer
mrjvs/42-transcendence pull request #29
Opened 2021-07-01 17:46 UTC by Maarten-Ramadan

2021-07-02 11:49 UTC, mrjvs requested changes

2021-07-02 11:49 UTC, mrjvs commented on vivid-client/src/components/Canvas.tsx
> +  }
dont use `client.id` as body. the body is client controlled so the client would be able to impersonate anybody.
instead use `@ConnectedSocket() client: Socket` in the event function to get the current client.
The client will have a `client.auth` if its logged in and you can access the id from that with `client.auth.id`

2021-07-02 11:49 UTC, mrjvs commented on vivid-server/src/modules/websocket/event.gateway.ts
> +  }
I recommend putting most of the logic inside a pong service and pass the client or server sockets through arguments, or something like it.
that way the events themselves here are pretty clean. (just like controllers. controllers and gateways are bare minimum. the services contain the actual logic)

2021-07-05 10:36 UTC, pmerku approved these changes

2021-07-05 11:42 UTC, mrjvs approved these changes

2021-07-05 11:42 UTC, mrjvs commented on vivid-client/src/hooks/useMessages.ts
> +
remove log?

2021-07-07 09:48 UTC, wbarendr approved these changes

2021-07-07 10:45 UTC, merged