Friend request handling on UserProfile modal
mrjvs/42-transcendence pull request #44
Opened 2021-07-17 14:43 UTC by Maarten-Ramadan

2021-07-17 14:52 UTC, mrjvs requested changes

2021-07-17 14:52 UTC, mrjvs commented on vivid-server/src/modules/friends/friends.service.ts
> +    user_2: UserEntity,
dont use entities here, they are hard to get and you only need the ids anyway
(also this break the comparison check on line 37)

2021-07-17 14:52 UTC, mrjvs commented on vivid-server/src/modules/friends/friends.service.ts
>        })
do a comparison check to see which order they need to be (`user_1 < user_2` is always true)

2021-07-17 14:52 UTC, mrjvs commented on vivid-client/src/components/styled/modals/UserProfile.modal.tsx
> +          (v: any) => v !== friendship,
friendship is null here

2021-07-20 08:11 UTC, mrjvs approved these changes

2021-07-21 12:06 UTC, mrjvs requested changes
Code looks good, although the approach for the friend request modal needs to change:
 1. request all friendship data when you open the modal (useFetch with onLoad: true)
 2. user input must be a username. not userid (that will require changes in the backend)
 3. dont request userdata on input of the textbox, that will spam the server. do it on button click

2021-07-22 09:17 UTC, mrjvs approved these changes

2021-07-26 12:15 UTC, mrjvs approved these changes

2021-07-26 12:16 UTC, wbarendr approved these changes

2021-07-26 12:21 UTC, merged